print('-----Escape Sequence Characters-----')
print("This is a backslash: \\")
print("It\'s Python!")
print("She said, \"Hello\"")
print("Line1\nLine2")
print("Item\tPrice")
print("12345\rabcd")
print("Helloo\b")
print("Hello\fWorld!")
print("Hello\vWorld!")
print("\a")
print("Text\0MoreText")
print("\x48\x69")
print("\110\151")
# print("\u3A9")
print("\U0001F600")
print("\N{BLACK HEART SUIT}")

print("\n-----Raw Strings(to avoid escaping)-----")
print(r"C:\Users\Shiva\Desktop")